var Style = require('./Pretzel.Style.js');

var DEFAULT_RADIUS = 1;
var DEFAULT_COLOR = 0xcccccc;
var DEFAULT_OPACITY = 1.0;
var DEFAULT_STYLE = new Style(DEFAULT_RADIUS, DEFAULT_COLOR, DEFAULT_OPACITY);

exports.DEFAULT_RADIUS = DEFAULT_RADIUS;
exports.DEFAULT_COLOR = DEFAULT_COLOR;
exports.DEFAULT_OPACITY = DEFAULT_OPACITY;
exports.DEFAULT_STYLE = DEFAULT_STYLE;
